export const GET_TASKS_FETCHING = 'GET_TASKS_FETCHING';
export const GET_TASKS_FULFILLED = 'GET_TASKS_FULFILLED';
export const GET_TASKS_REJECTED = 'GET_TASKS_REJECTED';
export const UPDATE_TASK_FETCHING = 'UPDATE_TASK_FETCHING';
export const UPDATE_TASK_FULFILLED = 'UPDATE_TASK_FULFILLED';
export const UPDATE_TASK_REJECTED = 'UPDATE_TASK_REJECTED';